const API_BASE_URL = import.meta.env.VITE_API_BASE_URL || 'http://localhost:5000'

export default {
    Root: "/",
    Login: "/api/v1/login",
    Logout: "/api/v1/logout",
    creditPlans: `${API_BASE_URL}/api/v1/credit-plans`,
    admin: {
        constants: "/admin/v1/constants",
        features: "/admin/v1/features",
        flashcards: "/admin/v1/flashcards",
        exercises: "/admin/v1/exercises",
        calculators: "/admin/v1/calculators",
        anatomy: "/admin/v1/anatomy",
        credits: "/admin/v1/credits",
        tags: "/admin/v1/tags",
        tagGroups: "/admin/v1/tag-groups",
        users: "/admin/v1/users",
        subscriptions: "/admin/v1/subscriptions",
        summaryNotes: "/admin/v1/summary-notes",
        mcq: "/admin/v1/mcq",
        chatbot: "/admin/v1/chatbot",
        pricing: "/admin/v1/pricing",
        skripsi: "/admin/v1/skripsi",
        oscePractice: "/admin/v1/oscePractice",
    },
    api: {
        calculators: "/api/v1/calculators",
        flashcards: "/api/v1/flashcards",
        exercises: "/api/v1/exercises",
        anatomy: "/api/v1/anatomy",
        features: "/api/v1/features",
        summaryNotes: "/api/v1/summary-notes",
        uploadImage: `/api/v1/upload/image`,
        mcq: "/api/v1/mcq",
        chatbot: "/api/v1/chatbot",
        pricing: "/api/v1/pricing",
        skripsi: "/api/v1/skripsi",
        oscePractice: "/api/v1/oscePractice",
        // OSCE Practice session endpoints
        osceMessages: (sessionId) => `/api/v1/oscePractice/sessions/${sessionId}/messages`,
        oscePhysicalExamMessages: (sessionId) => `/api/v1/oscePractice/sessions/${sessionId}/physical-exam/messages`,
        osceObservations: (sessionId) => `/api/v1/oscePractice/sessions/${sessionId}/observations`,
        osceDiagnoses: (sessionId) => `/api/v1/oscePractice/sessions/${sessionId}/diagnoses`,
        osceTherapies: (sessionId) => `/api/v1/oscePractice/sessions/${sessionId}/therapies`,
        osceEndSession: (sessionId) => `/api/v1/oscePractice/sessions/${sessionId}/end`,
    },
    pricing: {
        plans: `/api/v1/pricing/plans`,
        status: `/api/v1/pricing/status`,
        history: `/api/v1/pricing/history`,
        purchase: `/api/v1/pricing/purchase`,
        admin: {
            list: `/admin/v1/pricing`,
            detail: (id) => `/admin/v1/pricing/${id}`,
            create: `/admin/v1/pricing`,
            update: (id) => `/admin/v1/pricing/${id}`,
            toggle: (id) => `/admin/v1/pricing/${id}/toggle`,
        }
    },
}
