const API_BASE_URL = import.meta.env.VITE_API_BASE_URL || 'http://localhost:5000'

export default {
    Root: "/",
    Login: "/api/v1/login",
    Logout: "/api/v1/logout",
    creditPlans: `${API_BASE_URL}/api/v1/credit-plans`,
    admin: {
        constants: "/admin/v1/constants",
        features: "/admin/v1/features",
        flashcards: "/admin/v1/flashcards",
        exercises: "/admin/v1/exercises",
        calculators: "/admin/v1/calculators",
        diagnostic: "/admin/v1/diagnostic",
        anatomy: "/admin/v1/anatomy",
        atlas: "/admin/v1/atlas",
        credits: "/admin/v1/credits",
        tags: "/admin/v1/tags",
        tagGroups: "/admin/v1/tag-groups",
        users: "/admin/v1/users",
        userFeatureSubscriptions: (id) => `/admin/v1/users/${id}/feature-subscriptions`,
        featureSubscriptions: "/admin/v1/feature-subscriptions",
        subscriptions: "/admin/v1/subscriptions",
        summaryNotes: "/admin/v1/summary-notes",
        mcq: "/admin/v1/mcq",
        chatbot: "/admin/v1/chatbot",
        chatbotJournals: "/admin/v1/chatbot/journals",
        pricing: "/admin/v1/pricing",
        skripsi: "/admin/v1/skripsi",
        skripsiJournals: "/admin/v1/skripsi/journals",
        oscePractice: "/admin/v1/oscePractice",
        webinars: "/admin/v1/webinars",
        events: "/admin/v1/events",
        banners: "/admin/v1/banners",
        bannersReorder: "/admin/v1/banners/reorder",
        challenges: "/admin/v1/challenges",
        featureNodes: "/admin/v1/feature-nodes",
        featureNodeRecords: "/admin/v1/feature-nodes/records",
        autoLinkFlashcardDecks: "/admin/v1/feature-nodes/auto-link/flashcard-decks",
        flashcardsV2: "/admin/v2/flashcards",
        summaryNotesV2Admin: "/admin/v2/summary-notes",
        contentRelations: "/admin/v1/content-relations",
    },
    api: {
        calculators: "/api/v1/calculators",
        flashcards: "/api/v1/flashcards",
        flashcardsV2: "/api/v2/flashcards",
        flashcardNodes: "/api/v2-1/flashcards",
        reviewStats: "/api/v2/review/stats",
        reviewRate: "/api/v2/review/rate",
        reviewSession: "/api/v2/review/session",
        reviewCustomSessions: "/api/v2/review/custom-sessions",
        reviewSessions: "/api/v2/review/sessions",
        reviewSessionByUniqueId: (uid) => `/api/v2/review/sessions/${uid}`,
        featureNodes: "/api/v1/feature-nodes",
        exercises: "/api/v1/exercises",
        diagnostic: "/api/v1/diagnostic",
        anatomy: "/api/v1/anatomy",
        atlas: "/api/v1/atlas",
        features: "/api/v1/features",
        summaryNotes: "/api/v1/summary-notes",
        summaryNotesV2: "/api/v2/summary-notes",
        recentlyViewed: "/api/v1/recently-viewed",
        favorites: "/api/v1/favorites",
        uploadImage: `/api/v1/upload/image`,
        mcq: "/api/v1/mcq",
        chatbot: "/api/v1/chatbot",
        chatbotJournals: "/api/v1/chatbot/journals",
        pricing: "/api/v1/pricing",
        skripsi: "/api/v1/skripsi",
        skripsiJournals: "/api/v1/skripsi/journals",
        oscePractice: "/api/v1/oscePractice",
        tags: "/api/v1/tags",
        constants: "/api/v1/constants",
        webinars: "/api/v1/webinars",
        events: "/api/v1/events",
        banners: "/api/v1/banners",
        challenges: "/api/v1/challenges",
        challengeMyBadges: "/api/v1/challenges/my-badges",
        profile: "/api/v1/profile",
        // OSCE Practice session endpoints
        osceMessages: (sessionId) => `/api/v1/oscePractice/sessions/${sessionId}/messages`,
        oscePhysicalExamMessages: (sessionId) => `/api/v1/oscePractice/sessions/${sessionId}/physical-exam/messages`,
        osceObservations: (sessionId) => `/api/v1/oscePractice/sessions/${sessionId}/observations`,
        osceDiagnoses: (sessionId) => `/api/v1/oscePractice/sessions/${sessionId}/diagnoses`,
        osceTherapies: (sessionId) => `/api/v1/oscePractice/sessions/${sessionId}/therapies`,
        osceEndSession: (sessionId) => `/api/v1/oscePractice/sessions/${sessionId}/end`,
    },
    pricing: {
        plans: `/api/v1/pricing/plans`,
        status: `/api/v1/pricing/status`,
        history: `/api/v1/pricing/history`,
        purchase: `/api/v1/pricing/purchase`,
        admin: {
            list: `/admin/v1/pricing`,
            detail: (id) => `/admin/v1/pricing/${id}`,
            create: `/admin/v1/pricing`,
            update: (id) => `/admin/v1/pricing/${id}`,
            toggle: (id) => `/admin/v1/pricing/${id}/toggle`,
            reorder: `/admin/v1/pricing/reorder`,
        }
    },
}
