ALTER TABLE "flashcard_cards" ADD COLUMN "version" INTEGER NOT NULL DEFAULT 1;
ALTER TABLE "mcq_questions" ADD COLUMN "version" INTEGER NOT NULL DEFAULT 1;
ALTER TABLE "summary_notes" ADD COLUMN "version" INTEGER NOT NULL DEFAULT 1;
